apiVersion: crunchydata.com/v1
kind: Pgcluster
metadata:
  annotations:
    current-primary: hippo
  labels:
    crunchy-pgha-scope: hippo
    deployment-name: hippo
    name: hippo
    pg-cluster: hippo
    pgo-version: 4.6.2
    pgouser: admin
  name: hippo 
  namespace: pgo
spec:
  BackrestStorage:
    accessmode: ReadWriteMany
    matchLabels: ""
    name: ""
    size: 1G
    storageclass: ""
    storagetype: create
    supplementalgroups: ""
  PrimaryStorage:
    accessmode: ReadWriteMany
    matchLabels: ""
    name: hippo
    size: 1G
    storageclass: ""
    storagetype: create
    supplementalgroups: ""
  ReplicaStorage:
    accessmode: ReadWriteMany
    matchLabels: ""
    name: ""
    size: 1G
    storageclass: ""
    storagetype: create
    supplementalgroups: ""  
  annotations: {}
  ccpimage: crunchy-postgres-ha
  ccpimageprefix: registry.developers.crunchydata.com/crunchydata
  ccpimagetag: centos8-13.2-4.6.1
  clustername: hippo
  database: hippo
  exporter: true
  exporterport: "9187"
  limits: {}
  name: hippo
  namespace: pgo  
  pgBouncer:
    limits: null
    replicas: 1
    resources: null
    serviceType: ""
    tlsSecret: hippo-tls-keypair
  pgDataSource:
    restoreFrom: ""
    restoreOpts: ""
  pgbadgerport: "10000"
  pgoimageprefix: registry.developers.crunchydata.com/crunchydata
  podAntiAffinity:
    default: preferred
    pgBackRest: preferred
    pgBouncer: preferred
  port: "5432"
  tls:
    caSecret: postgresql-ca
    tlsSecret: hippo-tls-keypair
  tlsOnly: false
  tolerations: []
  user: hippo
  userlabels:
    pgo-version: 4.6.2