apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-app-config
  labels:
    app: todo-app
data:
  quarkus.datasource.jdbc.url: jdbc:postgresql://hippo-pgbouncer.pgo.svc.cluster.local:5432/hippo
  quarkus.datasource.username: micbn
  quarkus.datasource.password: SuperSecret1
  quarkus.swagger-ui.always-include: 'true'
  quarkus.ssl.native: 'false'
  